# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SIR": "00_models.ipynb"}

modules = ["models.py"]

doc_url = "https://binnisb.github.io/pandemic/"

git_url = "https://github.com/binnisb/pandemic/tree/master/"

def custom_doc_links(name): return None
